#!/usr/bin/env bash
set -euo pipefail

# Frozen four-artifact validation-v2 launcher.  Each artifact uses three
# workers (one per workload), so the four concurrent jobs occupy 12 workers.
# Do not edit this file after any validation-v2 seed has been opened.

WORKSPACE="${WORKSPACE:-/root/autodl-tmp/dai/research_workspace}"
DAI_PYTHON="${DAI_PYTHON:-/root/autodl-tmp/conda/envs/onlineggo39/bin/python}"
CKPT="${CKPT10:-$WORKSPACE/external/OnlineGGO/CMAES/logs/dai10k_resume_seed17_from_2k/checkpoints/optimal_update_model_10000.json}"
MAPDIR="$WORKSPACE/external/OnlineGGO/Guided-PIBT/guided-pibt/benchmark-lifelong/maps"
OUTDIR="$WORKSPACE/results/official_validation_v2"
LOGDIR="$WORKSPACE/logs/official_validation_v2"
RUNNER="$WORKSPACE/scripts/run_claim_aware_budgeted_validation.py"
SIM_SO="$WORKSPACE/external/OnlineGGO/CMAES/simulators/trafficMAPF_on/period_on_sim.cpython-39-x86_64-linux-gnu.so"

check_sha() {
  local expected="$1"
  local path="$2"
  local actual
  actual="$(sha256sum "$path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "SHA mismatch: $path expected=$expected actual=$actual" >&2
    exit 2
  fi
}

check_sha f22f75bade792e5723367af91d15c9301206b42b7a28f58600375ccbb691bd7c "$WORKSPACE/src/dai_lmapf/claim_runner.py"
check_sha 93a0c9f7e97e64b1b89264b207e8a7a3505522a58f2a9cbaeb5f30bfb921e57f "$RUNNER"
check_sha 98e8a99a8ad112b1b7024b28b21d141f3e471610a38b89d68f9248065fde475f "$WORKSPACE/configs/claim_validation_protocol_v2.json"
check_sha 6a1d5cd3a89efb64b2d25b93e943a340d7fccee2bbd56b53b35ec523eeef8843 "$WORKSPACE/reports/PROTOCOL_AMENDMENT_VALIDATION_V2.md"
check_sha e4d918075c9ea0e5be795572c16c64a843da2780294a407a190b989298008c8d "$CKPT"
check_sha 9e4b54722d67598f13f1bc2d4d0fb4121a94f79962923c184c1d269225e8c1a5 "$SIM_SO"
check_sha 866e664553959fb44af359276885e2e72192eaf36fd0f4abde3726474703cbb6 "$MAPDIR/warehouse_small_narrow_kiva.map"
check_sha 0e597b0c8ec25414d96bf2080ff5a60bbd3bb8f33f3622965807b7746f8a27dd "$MAPDIR/warehouse_small_kiva.map"

mkdir -p "$OUTDIR" "$LOGDIR"

SEEDS=(320019 241771 827130 693142 741084 12102 133633 876480 50620 131545)
COMMON=(
  --workspace "$WORKSPACE"
  --checkpoint "$CKPT"
  --checkpoint-sha256 e4d918075c9ea0e5be795572c16c64a843da2780294a407a190b989298008c8d
  --checkpoint-params-sha256 6f95c14a6afad6484a525f68e9809cf7c8a86fe48878a3d80abea67dd94abbac
  --split validation_v2
  --seeds "${SEEDS[@]}"
  --workloads stationary abrupt recurrent
  --warmup-time 200
  --horizon 2000
  --decision-window 20
  --release-interval 110
  --guard-suffix 4
  --sigma 0.75
  --context-match-threshold 0.05
  --context-recall-margin 0.02
  --context-min-score 0.10
  --context-min-gap 6
  --context-maintenance-age 25
  --context-maintenance-stability 0.20
  --jobs 3
)

PIDS=()
LABELS=()

launch() {
  local label="$1"
  local map_name="$2"
  local agents="$3"
  local output="$OUTDIR/$label.json"
  local csv="$OUTDIR/$label.csv"
  local log="$LOGDIR/$label.log"
  if [[ -e "$output" || -e "$csv" ]]; then
    echo "Refusing to overwrite protected artifact: $label" >&2
    exit 3
  fi
  "$DAI_PYTHON" "$RUNNER" "${COMMON[@]}" \
    --map-path "$MAPDIR/$map_name" \
    --agents "$agents" \
    --output "$output" >"$log" 2>&1 &
  PIDS+=("$!")
  LABELS+=("$label")
  echo "started label=$label pid=$!"
}

launch narrow_r020 warehouse_small_narrow_kiva.map 218
launch narrow_r035 warehouse_small_narrow_kiva.map 382
launch regular_r020 warehouse_small_kiva.map 255
launch regular_r035 warehouse_small_kiva.map 447

failed=0
for index in "${!PIDS[@]}"; do
  if wait "${PIDS[$index]}"; then
    echo "completed label=${LABELS[$index]}"
  else
    echo "failed label=${LABELS[$index]} log=$LOGDIR/${LABELS[$index]}.log" >&2
    failed=1
  fi
done

if [[ "$failed" -ne 0 ]]; then
  exit 4
fi

"$DAI_PYTHON" - "$OUTDIR" <<'PY'
import glob
import json
import os
import sys

outdir = sys.argv[1]
paths = sorted(glob.glob(os.path.join(outdir, "*.json")))
if len(paths) != 4:
    raise SystemExit(f"expected 4 artifacts, found {len(paths)}")
for path in paths:
    with open(path, encoding="utf-8") as stream:
        artifact = json.load(stream)
    runs = artifact["runs"]
    if artifact["status"] != "complete" or len(runs) != 390:
        raise SystemExit(f"incomplete artifact {path}")
    if len(artifact["methods"]) != 13 or len(artifact["seeds"]) != 10:
        raise SystemExit(f"protocol cardinality mismatch {path}")
    if any(not run["safety"]["passed"] for run in runs):
        raise SystemExit(f"safety failure {path}")
    if any(run["planner_timeouts"] for run in runs):
        raise SystemExit(f"planner timeout {path}")
    if any(not run["invariants"]["passed"] for run in runs):
        raise SystemExit(f"invariant failure {path}")
    if any(not run["budget"]["cap_satisfied"] for run in runs):
        raise SystemExit(f"budget cap failure {path}")
    print(f"audited {os.path.basename(path)} runs={len(runs)}")
print("VALIDATION_V2_MATRIX_COMPLETE")
PY
